version: "3.8"

networks:
  paddy-bridge:
    driver: bridge

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  
  paddy-auth:
    container_name: paddy-auth
    networks:
      paddy-bridge:
        aliases:
          - paddy.auth.io
    image: ghcr.io/opensrcerer/paddy-auth:master
    restart: on-failure
    ports:
      - "80:80"
    environment:
      - AUTH_PRIVATE_KEY=${BACKEND_MQTT_AUTHENTICATION_KEY}
      - MQTT_HOST=${BACKEND_MQTT_HOST}
      - MQTT_PORT=${BACKEND_MQTT_PORT}
      - MQTT_DEVICE_READ_TOPIC=${BACKEND_MQTT_DEVICE_READ_TOPIC}