version: "3.8"

networks:
  paddy-bridge:
    driver: bridge

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  
  paddy-auth:
    container_name: paddy-auth
    networks:
      paddy-bridge:
        aliases:
          - paddy.auth.io
    image: ghcr.io/opensrcerer/paddy-auth:master
    restart: on-failure
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost/auth/v1/health"]
#      interval: 5s
#      timeout: 30s
#      retries: 3
#      start_period: 10s
    ports:
      - "80:80"
    environment:
      - AUTH_PRIVATE_KEY=${BACKEND_MQTT_AUTHENTICATION_KEY}
      - QUARKUS_NEO4J_URI=${BACKEND_DB_URI}
      - QUARKUS_NEO4J_AUTHENTICATION_USERNAME=${BACKEND_DB_USER}
      - QUARKUS_NEO4J_AUTHENTICATION_PASSWORD=${BACKEND_DB_PASSWORD}