version: "3.8"

networks:
  paddy-bridge:
    driver: bridge

services:
  emqx:
    image: emqx:5.5.0
    container_name: emqx
    restart: on-failure
    environment:
      - EMQX_NODE_NAME=paddy-emqx@${BROKER_INTERNAL_IP}
      - EMQX_NODE_COOKIE=bonkersdbobcat
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx", "ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - "./emqx/emqx.conf:/opt/emqx/etc/emqx.conf:ro"
    network_mode: host
#    ports:
#      - "8083:8083"           # ws
#      - "8084:8084"           # wss
#      - "8883:8883"           # This is actually a TCP listener (check emqx.conf) but used like this because of terminating LB
#      - "18083:18083"         # web dashboard
#      - "4370:4370"           # Erlang port mapper (epmd) (clustering)
#      - "5369:5369"           # Cluster RPC port