version: "3.8"

networks:
  paddy-bridge:
    driver: bridge

services:
  emqx:
    image: emqx:5.5.0
    container_name: emqx
    restart: on-failure
    environment:
      - EMQX_NODE__NAME=paddy-emqx@${BROKER_INTERNAL_IP}
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx", "ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - "./emqx/emqx.conf:/opt/emqx/etc/emqx.conf:ro"
#    networks:
#      paddy-bridge:
#        aliases:
#          - node1.emqx.io
    ports:
      - "8883:1883" # Redirect mqtts traffic to mqtt because we are using a terminating LB
      - "8083:8083"
      - "8084:8084"
#      - "8883:8883"
      - "18083:18083"