version: "3.8"

networks:
  paddy-bridge:
    driver: bridge

services:
  neo4j:
    image: neo4j:5.16.0
    container_name: neo4j
    restart: on-failure
    volumes:
      - /home/chronos/neo4j/data:/data
      - /home/chronos/neo4j/logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/bonkersdbobcat