version: "3.8"

services:
  etcd:
    ports:
      - "4001:4001"
      - "2380:2380"
      - "2379:2379"
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.12
    environment:
      - ETCD_NAME=paddy-etcd
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://${ETCD_HOST_IP}:2379,http://${ETCD_HOST_IP}:4001
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${ETCD_HOST_IP}:2380
      - ETCD_INITIAL_CLUSTER=paddy-etcd=http://${ETCD_HOST_IP}:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=paddy-etcd
      - ETCD_LOG_LEVEL=debug
#      - ETCD_AUTO_TLS=true
#      - ETCD_PEER_AUTO_TLS=true
