name: paddy-etcd

services:
    etcd:
        ports:
            - 4001:4001
            - 2380:2380
            - 2379:2379
        container_name: etcd
        image: quay.io/coreos/etcd:v2.3.8
        command: -name etcd0 -advertise-client-urls
            http://${HostIP}:2379,http://${HostIP}:4001 -listen-client-urls
            http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls
            http://${HostIP}:2380 -listen-peer-urls http://0.0.0.0:2380
            -initial-cluster-token etcd-cluster-1 -initial-cluster
            etcd0=http://${HostIP}:2380 -initial-cluster-state new
        environment:
          - HostIP=${ETCD_HOST_IP}